/* samptcpip -> samp-http
 * A TCP/IP framework for people who would like to keep their sanity.
 *
 * Copyright (c) 2015 Pék Marcell
 * This project is covered by the MIT License, see the attached LICENSE
 * file for more details.
 *
 * samp-http.inc - the samp-http bootstrapper
 *
 */

 #include <socket>		// This library depends on BlueG's Socket Plugin
 #include <samptcpip/samp-http/config>
 #include <samptcpip/samp-http/main>